import type { Filing } from "../lib/filingsClient";
import { filingTypeColor, filingTypeLabel } from "../lib/filingsClient";
import { prettyDate } from "../lib/calendarUtils";
import "./DetailPanel.css";

// IPO Radar surfaces TWO artifacts per filing when a reportSlug is set:
//
//   1. Fact Sheet  — short one-pager, hosted in-house at /factsheet/<slug>.
//      Currently still generated by Manus and proxied via the same /factsheet
//      route (or pointed at the FACTSHEET_BASE) until insourcing lands.
//   2. Full Report — long-form 11-page initiation report, hosted in-house
//      at /reports/<slug>. Behind a (future) firewall.
//
// Both buttons are equally weighted in the UI — the editor decides per
// filing which artifact is most useful. EDGAR remains the secondary
// "Source filing" link.
//
// FACTSHEET_BASE kept as an env-overridable constant so we can still
// point at Manus while insourcing is in flight. Once the in-house
// /factsheet/<slug> route ships, set FACTSHEET_BASE to "" (empty) and
// the URL becomes a relative /factsheet/<slug> on this domain.
const FACTSHEET_BASE =
  (import.meta.env.VITE_FACTSHEET_BASE as string | undefined) ??
  "https://iporadar-jxwaypt6.manus.space";

function factSheetUrl(slug: string | undefined): string | null {
  if (!slug) return null;
  // If FACTSHEET_BASE is empty, default to the in-house relative path.
  // While Manus is still hosting, the existing path is /ipo/<slug>;
  // once we insource, the path becomes /factsheet/<slug>.
  if (FACTSHEET_BASE === "") {
    return `/factsheet/${encodeURIComponent(slug)}`;
  }
  return `${FACTSHEET_BASE}/ipo/${encodeURIComponent(slug)}`;
}

function reportUrl(slug: string | undefined): string | null {
  if (!slug) return null;
  return `/reports/${encodeURIComponent(slug)}`;
}

interface Props {
  selectedDate: string | null;
  filings: Filing[];
}

export default function DetailPanel(props: Props) {
  const selectedDate = props.selectedDate;
  const filings = props.filings;

  if (!selectedDate) {
    return (
      <aside className="detail-panel empty">
        <h3 className="panel-title">Select a date</h3>
        <p className="panel-empty-text">
          Click any day in the calendar to see SEC filing events for that date.
        </p>
      </aside>
    );
  }

  let countLabel = "";
  if (filings.length === 0) countLabel = "No filings on this date.";
  else if (filings.length === 1) countLabel = "1 filing";
  else countLabel = filings.length + " filings";

  return (
    <aside className="detail-panel">
      <h3 className="panel-title">{prettyDate(selectedDate)}</h3>
      <p className="panel-count">{countLabel}</p>

      {filings.length > 0 ? (
        <ul className="filing-list">
          {filings.map(function (f) {
            const chipStyle = { backgroundColor: filingTypeColor(f.filingType) };
            const factSheetHref = factSheetUrl(f.reportSlug);
            const reportHref = reportUrl(f.reportSlug);
            const hasArtifacts = factSheetHref !== null || reportHref !== null;
            return (
              <li key={f._id} className="filing-card">
                <header className="filing-card-header">
                  <span className="filing-type-chip" style={chipStyle}>{f.filingType}</span>
                  <span className="filing-type-label">{filingTypeLabel(f.filingType)}</span>
                </header>
                <h4 className="filing-company">{f.companyName}</h4>
                <div className="filing-meta">
                  {f.ticker ? <span className="meta-pill">{f.ticker}</span> : null}
                  {f.exchange ? <span className="meta-pill">{f.exchange}</span> : null}
                  {f.industry ? <span className="meta-pill subtle">{f.industry}</span> : null}
                </div>
                <div className="filing-actions">
                  {factSheetHref ? (
                    <a className="filing-primary-cta" href={factSheetHref} target="_blank" rel="noopener noreferrer">Fact Sheet</a>
                  ) : null}
                  {reportHref ? (
                    <a className="filing-primary-cta" href={reportHref} target="_blank" rel="noopener noreferrer">Full Report</a>
                  ) : null}
                  <a className="filing-source" href={f.edgarUrl} target="_blank" rel="noopener noreferrer">{hasArtifacts ? "Source filing" : "View on EDGAR"}</a>
                </div>
              </li>
            );
          })}
        </ul>
      ) : null}
    </aside>
  );
}
